### ISSUE TITLE
Allow passing additional arguments to mock build

### ISSUE THREAD

**Issue by msimacek** [rebase-helper/rebase-helper#178]
In Java world we have a special mock plugin `pm_request` that can handle automatic detection of buildrequires. It would be nice if I had some way to enable it (i.e. pass `--enable-plugin pm_request`) when using rebase-helper

**Comment by thozza** [comment]
Fixed by https://github.com/rebase-helper/rebase-helper/commit/d30d3ac2a595fa6825c2fae07157b8df038ca9cf
