### ISSUE TITLE
Source0: needs to bu updated for thousands of packages.

### ISSUE THREAD

**Issue by torsava** [rebase-helper/rebase-helper#186]
Hi!
The Python Package Index (PyPI) has decided to change the URL address to download tarballs/sources [0]. This means that possibly thousands of Python packages need to be updated with a new Source0 link.

The new URL address is:

```
https://files.pythonhosted.org/packages/source/p/positional/positional-1.1.0.tar.gz
```

Instead of the old:

```
https://pypi.python.org/ ...
```

**Do you think it would be beneficial to work this change into the `rebase-helper`? If so, I'd volunteer for the effort.**

[0] https://bitbucket.org/pypa/pypi/issues/438/backwards-compatible-un-hashed-package

Great day to all,
Tomas

**Comment by thozza** [comment]
Thank you for your interesting idea.

rebase-helper uses the Source0 from the SPEC for downloading new sources. If the URL does not exist, it would fail. In such case we could definitely try another URL if we find out the package is from PyPI. And if it works also use it in the rebased SPEC.

Having more general way of doing the changes is preferred. An idea from the top of my head would be to add some pre-download hook which can then run plugins, which modify the Source0 URL before download. Then we could have the change of URL of PyPI implemented as such pre-download plugin. However I think we will have to discuss the right approach before implementing anything.

@torsava do you know what is the timeline for PyPI changes?

**Comment by torsava** [comment]
That sounds like a very good system!

> @torsava do you know what is the timeline for PyPI changes?

Well, they switched to the new system a month ago, the old system no longer works and they gave no advanced warning what so ever (claiming the URL format was not an officially supported API). So much for a timeline. :)

**Comment by phracek** [comment]
Link to relevant code https://github.com/phracek/rebase-helper/blob/master/rebasehelper/specfile.py#L163
