### ISSUE TITLE
Rework Checker class

### ISSUE THREAD

**Issue by thozza** [rebase-helper/rebase-helper#190]
I think the class should be implemented in a way, that it gets the plugins from some default place when instantiated. Having to pass the dir name every time does not seem good to me. It may be also worth to instantiate the class on module import, so that we don't have to load all checker every time we instantiate the class on multiple places.

https://github.com/phracek/rebase-helper/commit/aefb8eee94802c171f288d353b4146a9d7c31197

**Comment by phracek** [comment]
Fixed by PR https://github.com/rebase-helper/rebase-helper/pull/213
