### ISSUE TITLE
Problem with downloading file

### ISSUE THREAD

**Issue by phracek** [rebase-helper/rebase-helper#192]
Archive is moved to different location.
~~~
phracek@unused-4-101: ~/work/Fedora/libpng ((50a7191...) %)$ rebase-helper 1.6.22
Results directory 'rebase-helper-results' exists, removing it

Failed to download file from URL ftp://ftp.simplesystems.org/pub/libpng/png/src/libpng16/libpng-1.6.21.tar.gz. Reason: '<urlopen error ftp error: [Errno ftp error] 550 libpng-1.6.21.tar.gz: No such file or directory>'
phracek@unused-4-101: ~/work/Fedora/libpng ((50a7191...) %)$ 
~~~

**Comment by phracek** [comment]
How to reproduce this issue:
~~~
fedpkg clone libpng && cd libpng
fedpkg switch-branch f24
# This checkout is the latest upstream update related to 1.6.21
git check 50a719132b8fe34293c8ab4d58e503a35159680c
# update to 1.6.22 version
rebase-helper 1.6.22
~~~

File libpng-1.6.21.tar.gz exists in directory:
~~~
phracek@unused-4-101: ~/work/Fedora/libpng ((50a7191...) %)$ ls -la *.tar.gz
-rw-rw-r--. 1 phracek phracek 1419334 Jul 19 16:16 libpng-1.6.21.tar.gz
phracek@unused-4-101: ~/work/Fedora/libpng ((50a7191...) %)$ 
~~~

~~~
phracek@unused-4-101: ~/work/Fedora/libpng ((50a7191...) %)$ rebase-helper 1.6.22
Results directory 'rebase-helper-results' exists, removing it

Failed to download file from URL ftp://ftp.simplesystems.org/pub/libpng/png/src/libpng16/libpng-1.6.21.tar.gz. Reason: '<urlopen error ftp error: [Errno ftp error] 550 libpng-1.6.21.tar.gz: No such file or directory>'
phracek@unused-4-101: ~/work/Fedora/libpng ((50a7191...) %)$ 
~~~
I would suggest if tarball exists and downloading failes then use tarball which exists in the directory.

**Comment by Jurisak** [comment]
After small investigation I found why we are twice downloading the first tarball. At first we are doing in _prepare_spec_objects on line 162. There is a creation of SpecFile and as a part of __init__ is downloading of tarball. Second case is in the same method on line 169. 

On this line we are calling self.spec_file.copy(self.rebase_spec_file_path) but what it do is that it creates new SpecFile instance with different path :D ... So no copying at all. (We are only copying .spec file by using shutil.copy()). Is there some unknown dependency which blocks doing this same copying (using shutil) for other files?
