### ISSUE TITLE
'The file has zero size' exception when HTTP response has no Content-length header

### ISSUE THREAD

**Issue by nforro** [rebase-helper/rebase-helper#193]
Sometimes github servers don't send _Content-length_ header in a HTTP response and rebase-helper fails with `The file has zero size`.

I don't have a solid reproducer, but I noticed it usually happens on the first download request after a period of inactivity. Try this URL for instance: https://github.com/fatih/vim-go/archive/v1.7.1.tar.gz

I think it would be better in this case to show some infinite progress indicator in place of the percentual one and let the download finish.

**Comment by phracek** [comment]
I have the same problem in Dockerfile. I will add it to GitHub soon.

**Comment by phracek** [comment]
https://github.com/rebase-helper/rebase-helper/pull/239

~~~
Rebase-helper version: 0.8.0
Updating the extra version
Tarball is not in absolute path /package_name/2.1.9.tar.gz trying to download one from URL https://github.com/upgrades-migrations/preupgrade-assistant/archive/2.1.9.tar.gz
Tarball is not in absolute path. Trying to download it from URL

Failed to download file from URL https://github.com/upgrades-migrations/preupgrade-assistant/archive/2.1.9.tar.gz. Reason: 'The file has zero size'. 
~~~

**Comment by nforro** [comment]
There are also FTP servers which don't send file length, for example `ftp://ftp.gnupg.org/`.
Downloading any file from such FTP server also leads to `The file has zero size` error.
