### ISSUE TITLE
Implementation spec_hooks

### ISSUE THREAD

**Issue by phracek** [rebase-helper/rebase-helper#238]
It would be useful to implement a spec_hooks which will modify SPEC files before building packages.
https://github.com/rebase-helper/rebase-helper/pull/237

**Comment by phracek** [comment]
This can be a first spec_hook for implementation https://github.com/rebase-helper/rebase-helper/pull/223

**Comment by nforro** [comment]
Spec hooks were re-implemented in PR #256.
