### ISSUE TITLE
Installing rebase-helper on non-system Python

### ISSUE THREAD

**Issue by junaruga** [rebase-helper/rebase-helper#285]
May I ask you a question about installing `rebase-helpr`?

I am trying to install `rebase-helpr` (latest master branch) on Python 3.6.1 installed from source code on Fedora 25.

```
$ pwd
/home/jaruga/git/rebase-helper

$ which python3
/usr/local/python-3.6.1/bin/python3

$ sudo /usr/local/python-3.6.1/bin/pip3 install .

$ which rebase-helper
/usr/local/python-3.6.1/bin/rebase-helper

$ rebase-helper --help
Traceback (most recent call last):
  File "/usr/local/python-3.6.1/bin/rebase-helper", line 11, in <module>
    load_entry_point('rebasehelper==0.9.0', 'console_scripts', 'rebase-helper')()
  File "/usr/local/python-3.6.1/lib/python3.6/site-packages/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/python-3.6.1/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/local/python-3.6.1/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2291, in load 
    return self.resolve()
  File "/usr/local/python-3.6.1/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2297, in resolve 
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/python-3.6.1/lib/python3.6/site-packages/rebasehelper/cli.py", line 30, in <module>
    from rebasehelper.application import Application
  File "/usr/local/python-3.6.1/lib/python3.6/site-packages/rebasehelper/application.py", line 28, in <module>
    import git 
ModuleNotFoundError: No module named 'git

$ sudo /usr/local/python-3.6.1/bin/pip3 install . -r requirements.txt

Traceback (most recent call last):
  File "/usr/local/python-3.6.1/bin/rebase-helper", line 11, in <module>
    load_entry_point('rebasehelper==0.9.0', 'console_scripts', 'rebase-helper')()
  File "/usr/local/python-3.6.1/lib/python3.6/site-packages/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/python-3.6.1/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/local/python-3.6.1/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/local/python-3.6.1/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/python-3.6.1/lib/python3.6/site-packages/rebasehelper/cli.py", line 30, in <module>
    from rebasehelper.application import Application
  File "/usr/local/python-3.6.1/lib/python3.6/site-packages/rebasehelper/application.py", line 32, in <module>
    from rebasehelper.specfile import SpecFile, get_rebase_name, spec_hooks_runner
  File "/usr/local/python-3.6.1/lib/python3.6/site-packages/rebasehelper/specfile.py", line 27, in <module>
    import rpm
ModuleNotFoundError: No module named 'rpm'
```

> https://github.com/rebase-helper/rebase-helper/blob/master/requirements.txt#L2

```
# This can not be installed from pip, on Fedora you need to install rpm-python{,3}
#rpm-python
```

* Which python package I need for `import rpm`? I could not find the `rpm-python` at https://pypi.python.org/pypi?%3Aaction=search&term=rpm&submit=search .

* Why do not we set `setuptools.setup` `install_requires` in `setup.py` to install runtime dependency packages automatically?

**Comment by junaruga** [comment]
> * Which python package I need for import rpm?

Ah it may be this module. Maybe it is not in pypi site.
https://github.com/rpm-software-management/rpm/blob/master/python/rpm/__init__.py

**Comment by nforro** [comment]
You won't find `rpm-python` on PyPI, because it's Fedora/RHEL specific.
You could install `python3-rpm` package (it used to be called `rpm-python3`, we should probably update the comment in `requirements.txt`), but that won't help you, since it uses `python3.5` runtime.
I suppose your only choice is to build [rpm python module](https://github.com/rpm-software-management/rpm/tree/master/python) from source.

The `rpm` module is also the reason why we don't support `install_requires`.

**Comment by junaruga** [comment]
@nforro ok, so I am going to send PR to update `requirements.txt`.

By the way, please keep this ticket to open without closing. Because I want to look for better solution about the `install_requires` and the `python3-rpm` package by myself.

**Comment by junaruga** [comment]
Good news.
I developed a installer to install `rpm-python` from `pip` or `install_requires`.
https://github.com/junaruga/rpm-py-installer

**Comment by junaruga** [comment]
- Way1: Set `--no-cache-dir` option in setup.py forcely.
- Control cache manually. Ref https://github.com/authomatic/gae_installer/blob/master/setup.py#L45

**Comment by nforro** [comment]
Perhaps you could add support also for [hawkey module](https://github.com/rpm-software-management/libdnf/tree/master/python/hawkey). It's just been added to [requirements.txt](https://github.com/rebase-helper/rebase-helper/blob/master/requirements.txt).

**Comment by junaruga** [comment]
Thanks for the feedback. OK I try to support it too.

**Comment by junaruga** [comment]
@nforro I asked the `libdnf` about Hawkey. and he said "Hawkey is going to die".
So, we should stop using `hawkey` in `rebase-helper`, shouldn't we?

```
> https://github.com/rpm-software-management/libdnf/issues/321
> Hawkey is going to die, libdnf will be available only through gobject introspection.
```

**Comment by nforro** [comment]
Well, I just started to use `hawkey` because of `split_nevra` function, which is the replacement for `rpmUtils.miscutils.splitFilename`. So what is the replacement for `hawkey.split_nevra`? I'm afraid there isn't any, so we'll probably have to create our own implementation.

**Comment by nforro** [comment]
@junaruga: I've opened issue https://github.com/rebase-helper/rebase-helper/issues/308.

**Comment by junaruga** [comment]
> So what is the replacement for hawkey.split_nevra?

Using `rpm` command?

```
$ rpm --queryformat "name: %{NAME}, version: %{VERSION}, release: %{RELEASE}, arch: %{ARCH}\n" -qp rubygem-sass-3.4.24-1.fc27.noarch.rpm
name: rubygem-sass, version: 3.4.24, release: 1.fc27, arch: noarch
```

**Comment by nforro** [comment]
Yes, we can use (and we do use) `rpm` module for this. But it extracts information from the package header and actually ignores the filename. And of course it needs the package to be physically accesible.

**Comment by junaruga** [comment]
Or to get name from the spec file, like this?

```
$ ./show_spec_macro.py ~/fed/rubygem-sass/rubygem-sass.spec %name
rubygem-sass
```

show_spec_macro.py
https://gist.github.com/junaruga/a27c875f7b1a7872b861b9db63f4ebb2

**Comment by nforro** [comment]
We use that as well, actually it can be simplified by using `rpm.spec()` directly.
But sometimes it is useful to be able to get the information just from filename, without having the package physically accesible.
I'm already working on an implementation based on `hawkey` sources.

**Comment by junaruga** [comment]
Oh, okay. 

> "working on an implementation based on hawkey sources."

That's cool!
Thanks.

**Comment by junaruga** [comment]
I would inform here as I was succeeded to install `rebase-helper` on non-system Python.

```
$ pwd
/home/jaruga/git/rebase-helper

$ which python3
/usr/local/python-3.6.1/bin/python3

$ sudo /usr/local/python-3.6.1/bin/pip3 install --no-cache-dir rpm-py-installer

$ sudo /usr/local/python-3.6.1/bin/pip3 install .

$ sudo /usr/local/python-3.6.1/bin/pip3 install . -r requirements.txt

$ /usr/local/python-3.6.1/bin/rebase-helper --help
usage: rebase-helper [-h] [-v] [-b | --comparepkgs-only COMPAREPKGS_DIR | -p]
...
```
