### ISSUE TITLE
Rebasing the upstream project's latest stable version without 1st argument

### ISSUE THREAD

**Issue by junaruga** [rebase-helper/rebase-helper#287]
I want to suggest a new feature.

Right now `rebase-helper`'s 1st argument is necessary regarding README.

https://github.com/rebase-helper/rebase-helper/blob/master/README.md

What I want to suggest is if a first argument is not specified, I want to rebase for the upstream project's latest stable version.
Because rebasing for latest stable version is popular workflow.

Rebase for the upstream project's version 3.1.10.

```
rebase-helper 3.1.10
```

Rebase for the upstream project's latest stable version.

```
rebase-helper
```

**Comment by nforro** [comment]
Similar thing is already proposed in #227, and we plan to implement it in a generic way (using plugins for different upstream providers).

**Comment by junaruga** [comment]
That's good news. Thanks. If this ticket is duplicated, feel free to close this ticket.

**Comment by junaruga** [comment]
To get latest stable version, can't we use Anitya that is used in PkgDB?

Anitya Project URL
https://github.com/release-monitoring/anitya
https://release-monitoring.org/

Example: rails (Ruby on Rails)
https://release-monitoring.org/project/4305/
