### ISSUE TITLE
ruby: Downloading wrong version ruby-13.3.0.tar.xz

### ISSUE THREAD

**Issue by junaruga** [rebase-helper/rebase-helper#315]
I tried to run `rebase-helper` for Fedora Ruby https://src.fedoraproject.org/rpms/ruby/blob/master/f/ruby.spec .

I expected to download below URL (Source0).
ftp://ftp.ruby-lang.org/pub/ruby/2.4/ruby-2.4.1.tar.xz
This is the latest version.

But `rebase-helper` trying to download invalid version `ruby-13.3.0.tar.xz`.

Do you know why?

```
$ pwd
/home/jaruga/fed/ruby

$ pip3 list | grep rebasehelper
rebasehelper          0.10.0 

$ rebase-helper 
Running 'anitya' versioneer
Determined latest upstream version '13.3.0'
Running 'PyPI URL Fix' spec hook
Running 'Typo fix' spec hook

Failed to download file from URL ftp://ftp.ruby-lang.org/pub/ruby/2.4/ruby-13.3.0.tar.xz. Reason: '<urlopen error ftp error: URLError("ftp error: error_perm('550 Failed to change directory.',)",)>'. 
```

**Comment by nforro** [comment]
Thanks for the report. Fixed in https://github.com/rebase-helper/rebase-helper/pull/317.
