### ISSUE TITLE
rubygem-byebug: Could not determine latest upstream version and no SOURCES argument specified!

### ISSUE THREAD

**Issue by junaruga** [rebase-helper/rebase-helper#318]
I ran `rebase-helper` latest master branch for https://src.fedoraproject.org/rpms/rubygem-byebug/blob/master/f/rubygem-byebug.spec

Do you know why is the message "Could not determine latest upstream version and no SOURCES argument specified!" shown?

This RPM spec file has Source0, though it is using tab as separator instead of space in the file.

```
$ pwd
/home/jaruga/fed/rubygem-byebug

$ pip3 list | grep rebasehelper
rebasehelper          0.10.0   /home/jaruga/git/rebase-helper

$ rebase-helper 
Results directory 'rebase-helper-results' exists, removing it
Running 'anitya' versioneer

Could not determine latest upstream version and no SOURCES argument specified!
```

**Comment by nforro** [comment]
This has nothing to do with `Source0`, it just failed to determine the latest upstream version using Anitya versioneer, because there is no entry for `rubygem-byebug` on https://release-monitoring.org/.
