### ISSUE TITLE
Disallow certain plugins

### ISSUE THREAD

**Issue by skisela** [rebase-helper/rebase-helper#320]
Determine package language to find out which Spec Hooks should not be run. 
Not running `PyPIURLFixHook` in other than python packages for example.

Add option to disallow/allow only some Spec Hooks to be run.

There should be an option to forbid certain spec_hooks/versioneers.

**Comment by nforro** [comment]
> Determine package language to find out which Spec Hooks should not be run.

This is resolved in commit 1ed4a7c8990412e212d233eca423008b854c5baf.

**Comment by nforro** [comment]
> Add option to disallow/allow only some Spec Hooks to be run.

This part is not implemented yet.
