### ISSUE TITLE
Adding git name and email in change log

### ISSUE THREAD

**Issue by junaruga** [rebase-helper/rebase-helper#352]
For example, for `ruby.spec`.

```
(venv) $ rebase-helper
...
(venv) $ diff ruby.spec rebase-helper-results/rebased-sources/ruby.spec 
24c24
< %global release 84
---
> %global release 1
1032a1033,1035
> * Sun Oct 15 2017 rebase-helper <rebase-helper@localhost.local> - 2.4.2-1
> - New upstream release 2.4.2
```

In this update, I want to include my user name, and email address.
Maybe the result of below commands.

```
$ git config user.name
Jun Aruga
$ git config user.email
jaruga@redhat.com
```

**Comment by nforro** [comment]
> Maybe the result of below commands.
> `$ git config user.name`
> `$ git config user.email`

That's exactly what is being done, see: https://github.com/rebase-helper/rebase-helper/blob/master/rebasehelper/specfile.py#L1298-L1299

Could you provide more information so we can investigate why it doesn't work for you?

**Comment by junaruga** [comment]
OK, let me check it.

**Comment by junaruga** [comment]
@nforro I found the reason.

https://github.com/rebase-helper/rebase-helper/blob/master/rebasehelper/utils.py#L817-L829

GitHelper#get_user, get_email methods use default user name and email when the command line `git config --get --global user.name` is failed.

But on virtual environment, the result is like this. `--global` does not work on virtual environment.
I want to remove `--global` from the command line if it is no problem.

```
(venv) $ git config --get --global user.name
(venv) $ echo $?
1

(venv) $ git config user.name
Jun Aruga
(venv) $ echo $?
0

(venv) $ git config --get user.name
Jun Aruga
(venv) $ echo $?
0
```

**Comment by junaruga** [comment]
Ah it's not virtualenv specified issue. It is reproduced on my normal local environment.

```
$ git config --get --global user.name
$ echo $?
1

$ git config user.name
Jun Aruga
$ echo $?
0

$ git config --get user.name
Jun Aruga
$ echo $?
0
```

**Comment by nforro** [comment]
I'm not sure why we used `--global` in the first place, but I guess it's not really necessary.
