### ISSUE TITLE
Do not add changelog if current version is latest

### ISSUE THREAD

**Issue by junaruga** [rebase-helper/rebase-helper#354]
For example, for `ruby.spec`.

```
(venv) $ rebase-helper
...
(venv) $ vi rebase-helper-results/rebased-sources/ruby.spec 
...
%changelog
* Sun Oct 15 2017 rebase-helper <rebase-helper@localhost.local> - 2.4.2-1
- New upstream release 2.4.2

* Mon Sep 18 2017 Pavel Valena <pvalena@redhat.com> - 2.4.2-84
- Update to Ruby 2.4.2.
...
```

If current version is latest version (2.4.2), I like `rebase-helper` does not append changelog comment.

**Comment by nforro** [comment]
Actually if a package is already in its latest version, rebase-helper should not do anything at all, it doesn't make much sense.

**Comment by junaruga** [comment]
> Actually if a package is already in its latest version, rebase-helper should not do anything at all,

Yeah, the behavior "if a package is already in its latest version, rebase-helper should not do anything at all" is much better.
