### ISSUE TITLE
RFE: complete automation

### ISSUE THREAD

**Issue by TomasTomecek** [rebase-helper/rebase-helper#462]
Thank you for making rebase-helper awesome. I absolutely love that tool and it saves me so much time.

I have an idea how to make it even better (sorry if there is an issue for that already).

What if rebase-helper would cover **every** manual task a maintainer needs to do?

Here is how I use rebase-helper now:

1. I run `rebase-helper x.y.z`.
2. If the build succeeds, I copy the rebased sources to the dist-git repo.
3. I run `fedpkg new-sources`.
4. I create a new commit.
5. I push the changes.
6. I build.

What I would love to see rebase-helper doing is:

1. I run `rebase-helper x.y.z`

And it performs all the things mentioned in points 2 up to 6.

**Comment by skisela** [comment]
@TomasTomecek Thanks for feedback and ideas!

You are right at the time all the steps are needed, except `step 2` might be exchanged by applying the generated `changes.patch` in `rebase-helper-results` directory.

Your idea is something we are trying to achieve. To be more exact, we were thinking of using the generated changes to create a pull request, which would trigger CI tests (if any are present) and then be accepted by the maintainer.

The same approach will likely be used for automatic rebases, which are momentarily disabled.

I think that would be ideal, as in case of modifying patches during the rebase, some bugs might be introduced, which should be revealed immediately after.

**Comment by TomasTomecek** [comment]
@skisela can I do the 2nd step with `--results-dir $PWD`?

**Comment by nforro** [comment]
@TomasTomecek: Not really, since `rebase-helper-results` is always appended to the path specified, so `--results-dir $PWD` is actually the default (`$PWD/rebase-helper-results`). Also the rebased files are located in another subdirectory (`$PWD/rebase-helper-results/rebased-sources`). But it shouldn't be a problem to implement an option to change this path.

**Comment by TomasTomecek** [comment]
ah, I see

I'm probably going to create a script which will do exactly what my original post says and as you start implementing some of those, I can update it over time

**Comment by skisela** [comment]
@TomasTomecek do I understand your intention correctly, that you want the files in `$PWD` be in a shape ready for a commit(push) right away?

As I mentioned in https://github.com/rebase-helper/rebase-helper/issues/462#issuecomment-371121197 maybe a little unclearly, the changes in dist-git files are stored in `rebase-helper-results/changes.patch`, therefore what I believe you want to do, is right after `rebase-helper` finishes call `git apply rebase-helper-results/changes.patch`.

But you are right, that this step should be automized be a `--apply-changes-patch` or `--do-not-apply-changes-patch`.

Please correct me, if I missed something in your proposal.

**Comment by TomasTomecek** [comment]
I actually missed that patch file, I was copying files as indicated by @nforro.

You get 100% right. All I really want is from this tool to update all my packages if tests pass. Automatically.

As I wrote above, I will try to do it and may even hook it to fedmsg and give it a shot.

**Comment by TomasTomecek** [comment]
closing since this is unrealistic and we also have packit
