### ISSUE TITLE
RFE: prompt user when there are unprocessed hunks in a patch

### ISSUE THREAD

**Issue by TomasTomecek** [rebase-helper/rebase-helper#565]
I forgot to check the rest of the file and there was one unprocessed hunk.

It would be lovely if the tool told me that there is an unprocessed hunk in the file and that I should correct it probably.

**Comment by nforro** [comment]
If by unprocessed hunks you mean unmerged entries, that should be fixed in PR #570. If you mean exiting a mergetool with exit code 0 while leaving some unresolved conflicts in a file, I'm afraid there is nothing rebase-helper can do about it, as git already considers such file successfully merged.

**Comment by TomasTomecek** [comment]
I actually indeed meant to look for `<<<`, `>>>` in the patch. Or maybe show the rebased patches to the user and ask if they are okay before doing the builds.

If you feel like this doesn't make any sense, feel free to close. My point here is that rebasing the same patch multiple times is not fun, especially when I made the mistake which frustrates me even more.

But in the end this may indeed be a responsibility of the git merge tool, not rebase-helper.

**Comment by nforro** [comment]
> I actually indeed meant to look for `<<<`, `>>>` in the patch.

We could do that, but merge markers are not fixed, they depend on merge driver used. But I guess it can't hurt to look for the default markers only.

> Or maybe show the rebased patches to the user and ask if they are okay before doing the builds.

This is actually something we plan to implement.

**Comment by nforro** [comment]
Implemented in PR #572. There is a downside to this approach though: as the file containing unresolved conflicts is being reset to its original state (before launching mergetool), even the already resolved conflicts are reset and have to be resolved again.

**Comment by TomasTomecek** [comment]
thank you! looking forward trying this out!
