### ISSUE TITLE
PyPI package

### ISSUE THREAD

**Issue by lachmanfrantisek** [rebase-helper/rebase-helper#574]
Hi,

is it possible to release rebase-helper on PyPI?

(My use case is to be able to install rebase-helper from virtualenv.)

Thank you in advance!

**Comment by junaruga** [comment]
After uploading it to pypi, I want the pypi image badge on the README.md like this. :)
https://github.com/junaruga/rpm-py-installer/blob/master/README.md

**Comment by lachmanfrantisek** [comment]
![PyPI](https://img.shields.io/pypi/v/rebase-helper.svg)
![PyPI - License](https://img.shields.io/pypi/l/rebase-helper.svg)
![PyPI - Python Version](https://img.shields.io/pypi/pyversions/rebase-helper.svg)
![PyPI - Status](https://img.shields.io/pypi/status/rebase-helper.svg)

```
![PyPI](https://img.shields.io/pypi/v/rebase-helper.svg)
![PyPI - License](https://img.shields.io/pypi/l/rebase-helper.svg)
![PyPI - Python Version](https://img.shields.io/pypi/pyversions/rebase-helper.svg)
![PyPI - Status](https://img.shields.io/pypi/status/rebase-helper.svg)
```

**Comment by nforro** [comment]
`rebase-helper` is now on PyPI: https://pypi.org/project/rebasehelper/

**Comment by lachmanfrantisek** [comment]
@nforro Nice, thank you!

**Comment by junaruga** [comment]
Nice!
