### ISSUE TITLE
.get_full_version() shows commit hash twice

### ISSUE THREAD

**Issue by TomasTomecek** [rebase-helper/rebase-helper#597]
Spec:
```
Version:        0.0.3.11.gc9956c9
Release:        1%{?dist}
```

Code:
```
print(rebasehelper.SpecFile(path).get_full_version())
```

Output:
```
'0.0.3.11.gc9956c9gc9956c9'
```

rebase-helper outputs the commit hash twice, even though it's there only once

Tarballs and SRPM generated afterwards:
```
-rw-rw-r--. 1 tt tt  19K Mar 15 12:47 ogr-0.0.3.11.gc9956c9.tar.gz
-rw-rw-r--. 1 tt tt  26K Mar 15 12:47 python-ogr-0.0.3.11.gc9956c9-1.fc29.src.rpm

```

**Comment by nforro** [comment]
Looking at the code, it seems to me `SpecFile.get_full_version()` method is useless and nonsensical. I'm going to remove it.
@TomasTomecek you probably want to use `SpecFile.get_version()` instead.

**Comment by TomasTomecek** [comment]
lol :D oki, will do, thank you
