### ISSUE TITLE
specfile._update_data hardcodes Source0 and blows if Source0 does not exist

### ISSUE THREAD

**Issue by TomasTomecek** [rebase-helper/rebase-helper#698]
```
/usr/lib/python3.7/site-packages/rebasehelper/specfile.py:267: in __init__                                                                                                   
    self._update_data()
/usr/lib/python3.7/site-packages/rebasehelper/specfile.py:327: in _update_data
    self._get_raw_source_string(0))
/usr/lib/python3.7/site-packages/rebasehelper/specfile.py:1102: in extract_version_from_archive_name
    url_base = os.path.basename(source_string).strip()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

p = None

    def basename(p):
        """Returns the final component of a pathname"""
>       p = os.fspath(p)
E       TypeError: expected str, bytes or os.PathLike object, not NoneType

p          = None

/usr/lib64/python3.7/posixpath.py:146: TypeError
```

I created a spec which uses Source2 as the only source and rebase-helper blows when it tries to parse it.

This is definitely a corner case, just wanted to report it if anyone stumbles upon this.

It would be ideal if rebase-helper was smart about this and iterated over all sources.

And now that I look into this, seems like a dupe of https://github.com/rebase-helper/rebase-helper/issues/561, creating anyway, feel free to close.

**Comment by nforro** [comment]
Yes, the problem is, it is hardcoded in a lot of places and not that trivial to fix :slightly_frowning_face:

**Comment by TomasTomecek** [comment]
but on the other hand, I wasn't even able to create a srpm using such spec with plain %setup or %autosetup - feels like that the %setup macros also hardcode Source0

Btw this is coming from https://github.com/packit-service/packit/issues/479

**Comment by nforro** [comment]
> feels like that the %setup macros also hardcode Source0

Yes, `%setup` always extracts Source0, unless it's explicitly disabled with [`-T` option](http://ftp.rpm.org/max-rpm/s1-rpm-inside-macros.html#S3-RPM-INSIDE-SETUP-T-OPTION).

To use `%setup` with Source2 only, you need to call it like this:

```spec
%setup -T -b 2
```
