### ISSUE TITLE
rebase-helper can't be installed on rawhide now

### ISSUE THREAD

**Issue by TomasTomecek** [rebase-helper/rebase-helper#715]
```
DEBUG util.py:593:  Error: 
DEBUG util.py:593:   Problem: conflicting requests
DEBUG util.py:593:    - nothing provides python3.8dist(marshmallow) < 3 needed by rebase-helper-0.18.0-1.fc32.noarch
```

Not sure if you are aware of this or this is already fixed.

**Comment by nforro** [comment]
We are aware, the problem is, [marshmallow-3.1.1 breaks copr](https://bugzilla.redhat.com/show_bug.cgi?id=1753270).
We'll probably have to resort to some kind of workaround.
