### ISSUE TITLE
ReplaceOldVersion hook must ignore versioned obsoletes and most likely also other dependency tags

### ISSUE THREAD

**Issue by nforro** [rebase-helper/rebase-helper#730]
See for example: https://src.fedoraproject.org/rpms/protobuf/blob/master/f/protobuf.spec#_45

**Comment by FrNecas** [comment]
I assume there are quite a lot of these tags (Conflicts, Requires, Recommends, etc). I would say that ignoring the whole preamble except for Patch/Source tags may be the best solution to this. Can you see any possible drawbacks?

**Comment by nforro** [comment]
This is still an issue if a tag [is defined by a macro](https://src.fedoraproject.org/rpms/fedora-obsolete-packages/blob/master/f/fedora-obsolete-packages.spec#_148).

The fix should be simple, do the check after macro expansion.

**Comment by nforro** [comment]
Not directly related to the original issue, but the hook assumes that there is a whitespace separating a tag from its value, and tracebacks when there is none.
I think the code should special-case preamble and avoid enumerating and parsing tags and use `SpecFile.tags` instead.

**Comment by FrNecas** [comment]
I don't think that expanding the line before doing the check will do the trick here. Apparently, `%obsolete` expands to `%obsoletes`, see

```
>>> MacroHelper.expand("%obsolete gegl 0.2.0-41")
'%obsolete gegl 0.2.0-41'
```

I will rewrite the hook and use `SpecFile.tags` for preamble, though I am not sure how we are going to handle the problem with dependencies defined by macros.

**Comment by nforro** [comment]
> Apparently, %obsolete expands to `%obsoletes`

What? It expands to itself, which means it doesn't expand at all, which happens I suppose because you are not doing it in the context of the spec file that defines the macro.

**Comment by FrNecas** [comment]
Oh, my bad, I thought that it is a macro defined by rpm. Now I see it is defined in the spec file so expanding will work.
