### ISSUE TITLE
packit usage of SpecFile.set_version breaks the spec file

### ISSUE THREAD

**Issue by msehnout** [rebase-helper/rebase-helper#732]
I'd like to use this command for version generation, so that I can build RPM locally:
```
Version:        %(python3 %{S:setup.py} --version)
```
but I'd also like to use packit to replace the whole macro with explicit version when it creates the content for dist-git. Unfortunately the result looks like this:
```diff
-Version:        %(python3 %{S:setup.py} --version)
+Version:        %(python3 %{S:setup.py} 3.23.g6216a0b
```
Would it be possible to fix this? I found that this code is responsible for the change, but since it is general for all tags I'm not sure how to change it and not break for others.
https://github.com/rebase-helper/rebase-helper/blob/1e9352f6943c87ee48a2002862e2f3245a241e44/rebasehelper/specfile.py#L694

This is the place where Packit calls rebase-helper:
https://github.com/packit-service/packit/blob/master/packit/upstream.py#L387

**Comment by FrNecas** [comment]
Thanks a lot for the report!

I tried reproducing the problem but unfortunately failed to do so. Am I assuming correctly that the following behaviour is what you are looking for?

```
>>> spec.spec_content.section('%package')[5]
'Version:        %(python3 %{S:setup.py} --version)'
>>> spec.set_version('3.23.g6216a0b')
>>> spec.spec_content.section('%package')[5]
'Version:        3.23.g6216a0b'
```

Perhaps the version passed by packit to `SpecFile.set_version` is incorrect?

**Comment by msehnout** [comment]
Thank you for a prompt response and yes, this is what I would expect. I'll check what packit provides to `set_version`.

**Comment by FrNecas** [comment]
I see the issue https://github.com/packit-service/packit/issues/567 has already been closed. Do I assume correctly that the problem has been fixed? Can we close this issue?

**Comment by msehnout** [comment]
Yes, I think we can.
