### ISSUE TITLE
Patch applied upstream is not removed

### ISSUE THREAD

**Issue by lubomir** [rebase-helper/rebase-helper#772]
My spec file contains a patch backported from upstream repo.

rebase-helper fails because the new rpm fails to build - it can not apply the patch because it does not change anything.

Replication steps:

```
fedpkg clone python-productmd
cd python-productmd
git checkout 6ad409439b0cf11572a99047a0736dff86f413b8
rebase-helper 1.24
```

I would expect rebase helper to drop the patch. Using `--disable-inapplicable-patches` doesn't change anything.

**Comment by nforro** [comment]
Thanks for the report. The patch is ignored because it's specified as a URL, and unfortunately `SpecFile._get_patch_strip_options()` doesn't handle that.
