### ISSUE TITLE
rebase-helper can't figure out patches when they stored in a different dir than a spec file

### ISSUE THREAD

**Issue by TomasTomecek** [rebase-helper/rebase-helper#798]
We are working with CentOS dist-git right now and the structure is a little different than what we have in Fedora. CentOS stores spec files in SPECS dir, while patches and additional files are stored in SOURCES dir.

Unfortunately, when I try to use rebase-helper for this setup, it can't figure out the patches :/

```
$ git clone git@github.com:TomasTomecek/centos-gnome-settings-daemon.git

$ cd centos-gnome-settings-daemon
$ git checkout c8s

$ ipython3

In [1]: from rebasehelper.specfile import SpecFile                                    

In [2]: s = SpecFile("SPECS/gnome-settings-daemon.spec", sources_location="SOURCES/") 

In [3]: s.get_applied_patches()            
Out[3]: []
```

At this point, applied_patches should yield a list of actual patches which are applied as you can see in the spec.

Am I doing something wrong?

**Comment by nforro** [comment]
The issue here is that *Source0* is missing, so `rpm` fails to parse the spec and `SpecFile` falls back to parsing ignoring missing sources. You have to download the missing source and parse the spec again:

```python
s = SpecFile("SPECS/gnome-settings-daemon.spec", sources_location="SOURCES/")
s.download_remote_sources()
s.update()
s.get_applied_patches()
```

Perhaps we should make that a default?

**Comment by TomasTomecek** [comment]
okay, didn't realize that, thank you very much!
