### ISSUE TITLE
openSUSE python-rpm-macros %python_subpackages causes parse failure

### ISSUE THREAD

**Issue by jayvdb** [rebase-helper/rebase-helper#831]
Running rebase-helper in https://build.opensuse.org/package/show/devel:languages:python/python-atpublic

```
> rebase-helper
INFO: rebase-helper version 0.23.1
INFO: Running 'pypi' versioneer
INFO: Determined latest upstream version '2.1.1'
ERROR: Failed to parse SPEC file: error: line 33: Unknown tag: could not find spec file at path: /tmp/tmprkwnbw3m
```

Line 33 is %python_subpackages , which is installed in my system, from https://github.com/openSUSE/python-rpm-macros

**Comment by jayvdb** [comment]
"could not find spec file at path" comes from the rpm lua layer, due to https://github.com/openSUSE/python-rpm-macros/blob/69783238fb6a88c66060f13d973bad008792017d/macros.lua#L331 during the expansion of `%python_subpackages`

Note the same type of macros exist at https://opendev.org/openstack/rpm-packaging/src/branch/master/openstack/openstack-macros/macros.openstack-singlespec  .  However it is a bit different, notably `specpath = ...` has a loop uncommented, whereas in at https://github.com/openSUSE/python-rpm-macros/blob/69783238fb6a88c66060f13d973bad008792017d/macros.lua#L62 it is just `%_specfile` and the loop is commented out.

Anyways, back to openSUSE, I can get past this by adding `local specpath = rpm.expand("%{_specfile}")\` before the `io.open`, so it seems the value of `specpath` from `_python_scan_spec` isnt being made available inside `%python_subpackages`.

After that, I see the following, which shows that Python 3.6 is being selected instead of Python 3.8 which I should be building against.
```
...
INFO: git-rebase operation to atpublic-2.1.1 is ongoing...
flags 1
INFO: Building source package for python-atpublic version 1.0
INFO: Building SRPM
INFO: Building SRPM finished successfully
INFO: Building source package for python-atpublic version 2.1.1
INFO: Building SRPM
INFO: Building SRPM finished successfully
python36-devel not installed

Some build dependencies are missing. Do you want to install them now [Y/n]? 
...
$ cat /home/jayvdb/projects/osc/devel:languages:python/python-atpublic/rebase-helper-results/old-build/RPM/build.log
specfile is /tmp/rebase-helper-t35k2zj_/rpmbuild/SPECS/python-atpublic.spec
sh: /usr/bin/python3.6: No such file or directory
sh: /usr/bin/python3.6: No such file or directory
sh: /usr/bin/python3.6: No such file or directory
error: Failed build dependencies:
        python36-devel is needed by python-atpublic-1.0-0.x86_64
        python36-setuptools is needed by python-atpublic-1.0-0.x86_64
        python38-devel is needed by python-atpublic-1.0-0.x86_64
        python38-setuptools is needed by python-atpublic-1.0-0.x86_64
Installing /home/jayvdb/projects/osc/devel:languages:python/python-atpublic/rebase-helper-results/old-build/SRPM/python-atpublic-1.0-0.src.rpm
```

If I then edit `/usr/lib/rpm/macros.d/macros.python_all`, and limit `%pythons`, effectively forcing Tumbleweed (c.f. https://github.com/rebase-helper/rebase-helper/issues/830#issuecomment-735553199) by removing python36 and python38
```
%pythons %{?!skip_python2:python2} %{?!skip_python3:python3}
```
Bingo, the rebase works as expected when using `--buildtool=rpmbuild`, in that it fails because the new  source no longer contains the tests.

**Comment by nforro** [comment]
I don't think there is anything we can do in rebase-helper to fix this.
