### ISSUE TITLE
Support .changes files

### ISSUE THREAD

**Issue by jayvdb** [rebase-helper/rebase-helper#832]
openSUSE requires the changelog be in the dedicated .changes file accompanying the .spec .

https://en.opensuse.org/openSUSE:Creating_a_changes_file_(RPM)

It looks like there is some changelog splitting occurring also in Fedora, but I am not sure of the details.
https://fedoraproject.org/wiki/Changes/rpm_level_auto_release_and_changelog_bumping

It might also be helpful to be able to disable changelog entry addition (`--no-changelog-entry`?), which is a less invasive change that I could undertake without further guidance, and would suffice as an interim step for openSUSE support.

**Comment by nforro** [comment]
> It looks like there is some changelog splitting occurring also in Fedora, but I am not sure of the details. https://fedoraproject.org/wiki/Changes/rpm_level_auto_release_and_changelog_bumping

Yes, but there isn't (and there won't be) a single unified way of storing changelog entries, so we can't really support that in rebase-helper.

As for .changes files support, you are welcome to propose a PR and I'll be glad to review and merge it, but I'm going to close this issue for now.
