### ISSUE TITLE
interacting with SpecFile class may result in printing stuff to STDERR

### ISSUE THREAD

**Issue by TomasTomecek** [rebase-helper/rebase-helper#833]
For example loading a spec file prints an error:
```
> /home/tt/g/user-cont/packit/packit/base_git.py(102)specfile()        
    101             import ipdb; ipdb.set_trace()
--> 102             self._specfile = Specfile(                                                 
    103                 self.absolute_specfile_path, self.absolute_source_dir

ipdb> n                                        
error: Unterminated {: {lua: if string.match(rpm.expand("%glibcsrcdir"), "^glibc%-[0-9.]+$") then
```

Is there a way to suppress the error line?

Some operations even do it multiple times:
```
> /home/tt/g/user-cont/packit/packit/specfile.py(104)set_spec_version()
    103 
--> 104             self.update_changelog_in_spec(changelog_entry)
    105 

ipdb> n                                        
error: Unterminated {: {lua: if string.match(rpm.expand("%glibcsrcdir"), "^glibc%-[0-9.]+$") then
error: Unterminated {: {lua: if string.match(rpm.expand("%glibcsrcdir"), "^glibc%-[0-9.]+$") then
error: Unterminated {: {lua: if string.match(rpm.expand("%glibcsrcdir"), "^glibc%-[0-9.]+$") then
```
(update_changelog_in_spec is our thin wrapper on top of SpecFile.update_changelog)

The main reason I am opening this issue are these lines:
```
Patch glibc-revert-mknod-compat.patch does not exist
Patch glibc-revert-fxstat-compat.patch does not exist
Patch glibc-deprecated-selinux-nscd.patch does not exist
Patch glibc-deprecated-selinux-makedb.patch does not exist
Patch glibc-fedora-nsswitch.patch does not exist
Patch glibc-python3.patch does not exist
Patch glibc-c-utf8-locale.patch does not exist
Patch glibc-cs-path.patch does not exist
Patch glibc-nscd-sysconfig.patch does not exist
Patch glibc-rh1070416.patch does not exist
Patch glibc-fedora-__libc_multiple_libcs.patch does not exist
Patch glibc-fedora-localedata-rh61908.patch does not exist
Patch glibc-rh819430.patch does not exist
Patch glibc-rh827510.patch does not exist
Patch glibc-fedora-manual-dircategory.patch does not exist
Patch glibc-fedora-localedef.patch does not exist
Patch glibc-rh741105.patch does not exist
Patch glibc-fedora-linux-tcsetattr.patch does not exist
Patch glibc-rh697421.patch does not exist
Patch glibc-fedora-nscd.patch does not exist
```
They are not an error since packit is going to create those files.

Can we make the rpm parser to not write those?

**Comment by nforro** [comment]
Actually, these are two different issues. The first error, `Unterminated {:`, originates [here](https://github.com/rebase-helper/rebase-helper/blob/c67c9140207091e971ac19ffb377a4751b06cf83/rebasehelper/tags.py#L162), while those `Patch does not exist` errors originate [here](https://github.com/rebase-helper/rebase-helper/blob/master/rebasehelper/specfile.py#L302).

I'm going to fix the first issue, since it's clearly a bug (parsing part of a multiline macro obviously has to end up with an error, and it needs to be suppressed).

The second issue is actually an error from rebase-helper point of view. You should be able to suppress it (and other errors) by disabling `rebasehelper.specfile` logger:

```python
import logging
logging.getLogger('rebasehelper.specfile').disabled = True
```

**Comment by TomasTomecek** [comment]
Thanks for info! Makes sense to me, I am going to tinker with rebase-helper logging in packit then.

**Comment by nforro** [comment]
Maybe it would make sense to disable the logging by default. In fact I thought it was the default, but apparently it isn't.
