### ISSUE TITLE
rebase-helper stucks when "INFO: git-rebase operation to reflections-0.10.1 is ongoing..."

### ISSUE THREAD

**Issue by didiksupriadi41** [rebase-helper/rebase-helper#874]
I'm running F34.
Executing `rebase-helper` gives me this output:

```
[dsupriadi@fedora reflections]$ rebase-helper 0.10.1
INFO: rebase-helper version 0.26.0
WARNING: Results directory 'rebase-helper-results' exists, removing it
INFO: Running 'commit-hash-updater' spec hook
INFO: Running 'escape-macros' spec hook
INFO: Running 'paths-to-rpm-macros' spec hook
INFO: Running 'replace-old-version' spec hook
INFO: Running 'typo-fix' spec hook
INFO: Downloading file from URL https://github.com/ronmamo/reflections/archive/0.10.1/reflections-0.10.1.tar.gz
    [<=>                           ]    73.40K   in 00:00:00 
INFO: Running checks on source files using 'licensecheck'
INFO: git-rebase operation to reflections-0.10.1 is ongoing...
```
and then it stucks.

here's `strace rebase-helper 0.10.1` output:
https://paste.centos.org/view/a1ea4117

**Comment by nforro** [comment]
Hi, thanks for the report. Sorry, I can't reproduce this, I suppose it has something to do with your system.
The paste is no longer available, but it would probably be better if you could attach the `debug.log` file that you can find in `rebase-helper-results/logs`.

**Comment by didiksupriadi41** [comment]
Here you go, but I'm not sure it's useful though.
- [debug.log](https://github.com/rebase-helper/rebase-helper/files/7469420/debug.log)
- [info.log](https://github.com/rebase-helper/rebase-helper/files/7469426/info.log)
- [verbose.log](https://github.com/rebase-helper/rebase-helper/files/7469429/verbose.log)

because it stucks, I hit `Ctrl-C` immediately.


From `strace`, I see it keeps looping:
[strace.log](https://github.com/rebase-helper/rebase-helper/files/7469475/strace.log)

From `top`:
```
                      `- /usr/bin/python3 /usr/bin/rebase-helper 0.10.1               
                          `- git cat-file --batch-check                               
                          `- git cat-file --batch                                     
                          `- git cat-file --batch-check                               
                          `- git cat-file --batch                                     
                          `- git cat-file --batch-check                               
                          `- git cat-file --batch                                     
```

BUT I do managed to run `rebase-helper` in a container though I'm not satisfied with that. :confused:

**Comment by didiksupriadi41** [comment]
`s/it's/they're`

**Comment by nforro** [comment]
Thanks, you are right, there is nothing useful in the logs. And thanks for the strace output, it helped. It's `init.defaultBranch` set to `main` in git configuration that causes this. I'll fix it ASAP.

**Comment by didiksupriadi41** [comment]
Thank you :+1:
